service: java-api
# app and org for use with dashboard.serverless.com
app: website
org: foodbanksy

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  runtime: java8
  region: eu-west-2
  
package:
  artifact: target/api.jar

functions:
  currentTime:
    handler: org.foodbanksy.serverless.Handler
    events:
      - http:
          path: ping
          method: get
